[book]
title = "Project Polyhedral (Pre-Release Playtest Material)"
authors = ["Sean Quinn"]
description = "A modern, modular role-playing and storytelling game system."
language = "en"
multilingual = false
src = "src"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/polyhedralpress/project-polyhedral"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/polyhedralpress/project-polyhedral/edit/main/polyhedral/{path}"

[build]
build-dir = "../dist/polyhedral"
create-missing = false

[preprocessor.tera]
